# Site settings
title: Wilson A Rawlings
header-img: img/home-bg.jpg
email: me@wilsonrawlings.com
copyright_name: Wilson A Rawlings
description: "portfollio and Resume for Wilson A Rawlings"
baseurl: ""
url: "http://j.wilsonrawlings.com"
twitter_username: 
github_username:  wilsonrawlings
facebook_username:  rawlingswa
email_username:  me@wilsonrawlings.com
instagram_username: wilson_rawlings

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
